version: '3'

services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: someprestashop
            MYSQL_DATABASE: prestashop
            MYSQL_USER: prestashop
            MYSQL_PASSWORD: prestashop
    prestashop:
        build: .
        image: apachefpm-prestashop
        command: web
        ports:
            - "80:80"
        restart: always
    php:
        depends_on:
            - db
        image: apachefpm-prestashop
        command: fpm
        restart: always
        environment:
            DB_SERVER: db
            DB_USER: prestashop
            DB_PASSWD: prestashop
