version: '3'

services:
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: someprestashop
            MYSQL_DATABASE: prestashop
            MYSQL_USER: prestashop
            MYSQL_PASSWORD: prestashop
    prestashop:
        build: .
        depends_on:
            - db
        image: apache-prestashop
        ports:
            - "80:80"
        restart: always
        environment:
            DB_SERVER: db
            DB_USER: prestashop
            DB_PASSWD: prestashop
